[book]
multilingual = false
src = "src"
title = "Documentation for Mozilla localizers"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/mozilla-l10n/localizer-documentation/"
edit-url-template = "https://github.com/mozilla-l10n/localizer-documentation/edit/main/{path}"
no-section-label = true

[output.html.redirect]
# These redirects are only going to work on https://mozilla-l10n.github.io/localizer-documentation
"tools/pontoon/search_filters.html" = "https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translation_workspace.html#search"
"tools/pontoon/ui.html" = "https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translation_workspace.html"
"tools/pontoon/workflow.html" = "https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/translate.html#workflow-example"
